//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22-Nov-18 11:47:15 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace OkooneBlogger.Data
{
    public partial class User {

        public User()
        {
            this.Articles = new List<Article>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string FullName
        {
            get;
            set;
        }

        public virtual string Username
        {
            get;
            set;
        }

        public virtual string Email
        {
            get;
            set;
        }

        public virtual string Password
        {
            get;
            set;
        }

        public virtual System.DateTime? Date
        {
            get;
            set;
        }

        public virtual IList<Article> Articles
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
